// File: ClkDriver.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 13:48:52 2021


`timescale 1ns/10ps

module ClkDriver (
    clk
);


output [0:0] clk;
reg [0:0] clk;




initial begin: CLKDRIVER_DRIVE_CLK
    while (1'b1) begin
        # 5;
        clk <= 1;
        # 5;
        clk <= 0;
    end
end

endmodule
