// File: AveragingFilter2.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 14:19:15 2021


`timescale 1ns/10ps

module AveragingFilter2 (
    clk,
    reset,
    data,
    average
);


input [0:0] clk;
input [0:0] reset;
input [7:0] data;
output [7:0] average;
reg [7:0] average;

reg [15:0] datastream;



always @(posedge clk) begin: AVERAGINGFILTER2_UPDATE_PREVIOUS
    if (reset) begin
        datastream <= Signal(0);
    end
    else begin
        datastream <= (($signed({1'b0, data}) * (2 ** (16 - 8))) + datastream[16-1:8]);
    end
end


always @(reset, datastream) begin: AVERAGINGFILTER2_ASSIGN_AVERAGE
    
    if (reset) begin
        average = Signal(0);
    end
    else begin
        average = ((sum(datastream) + 1) >>> 1);
    end
end

endmodule
