// File: AveragingFilter1.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 13:57:07 2021


`timescale 1ns/10ps

module AveragingFilter1 (
    clk,
    reset,
    data,
    average
);


input [0:0] clk;
input [0:0] reset;
input [9:0] data;
output [9:0] average;
reg [9:0] average;

reg [9:0] previous;



always @(posedge clk) begin: AVERAGINGFILTER1_UPDATE_PREVIOUS
    if (reset) begin
        previous <= Signal(0);
        average <= Signal(0);
    end
    else begin
        average <= (((previous + data) + 1) >>> 1);
        previous <= data;
    end
end

endmodule
